// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package userService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
