// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package userService;

public final class UserServiceImpl {
  private UserServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userService.proto\022\013userService\"2\n\014Logi" +
      "nRequest\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\">\n\rLoginResponse\022\027\n\017responseMessage" +
      "\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\rLogoutRe" +
      "quest\022\020\n\010userName\030\001 \001(\t\"?\n\016LogoutRespons" +
      "e\022\027\n\017responseMessage\030\001 \001(\t\022\024\n\014responseCo" +
      "de\030\002 \001(\005\"\007\n\005Empty2\224\001\n\013UserService\022@\n\005log" +
      "in\022\031.userService.LoginRequest\032\032.userServ" +
      "ice.LoginResponse\"\000\022C\n\006logout\022\032.userServ" +
      "ice.LogoutRequest\032\033.userService.LogoutRe" +
      "sponse\"\000B \n\013userServiceB\017UserServiceImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userService_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userService_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LoginRequest_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_userService_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_userService_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_userService_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_userService_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LogoutRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_userService_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_userService_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_userService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_userService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
