// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataBaseService.proto

package databaseService;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataBaseService.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
