// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataBaseService.proto

package databaseService;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataBaseService.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
